//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaboradorDescuento
    {
        public int idColaborador { get; set; }
        public int idDescuento { get; set; }
        public int idTipoDescuento { get; set; }
        public decimal monto { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual TipoDescuento TipoDescuento { get; set; }
    }
}
