//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colaborador()
        {
            this.ReferenciaColaborador = new HashSet<ReferenciaColaborador>();
            this.EmpresaColaborador = new HashSet<EmpresaColaborador>();
            this.DatoFamiliar = new HashSet<DatoFamiliar>();
            this.DatosAcademicos = new HashSet<DatosAcademicos>();
            this.DatosLaborales = new HashSet<DatosLaborales>();
            this.DetallePlanilla = new HashSet<DetallePlanilla>();
            this.ColaboradorDescuento = new HashSet<ColaboradorDescuento>();
            this.Identificacion = new HashSet<Identificacion>();
            this.Direcciones = new HashSet<Direcciones>();
            this.Bonos = new HashSet<Bonos>();
        }
    
        public decimal idColaborador { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string nombre3 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string apellido3 { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public decimal idEstadoCivil { get; set; }
        public decimal idProfesion { get; set; }
        public decimal idPuesto { get; set; }
        public string username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciaColaborador> ReferenciaColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaColaborador> EmpresaColaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatoFamiliar> DatoFamiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosAcademicos> DatosAcademicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosLaborales> DatosLaborales { get; set; }
        public virtual CuentaDeposito CuentaDeposito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePlanilla> DetallePlanilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColaboradorDescuento> ColaboradorDescuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Identificacion> Identificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direcciones> Direcciones { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Profesion Profesion { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonos> Bonos { get; set; }
    }
}
