//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoFamiliar
    {
        public int idColaborador { get; set; }
        public int idDatoFamiliar { get; set; }
        public int idParentezco { get; set; }
        public int idProfesion { get; set; }
        public string nombre { get; set; }
        public int edad { get; set; }
        public string telefono { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Parentezco Parentezco { get; set; }
        public virtual Profesion Profesion { get; set; }
    }
}
