//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePlanilla
    {
        public decimal idPlanilla { get; set; }
        public decimal idColaborador { get; set; }
        public decimal idFormaPago { get; set; }
        public decimal año { get; set; }
        public decimal mes { get; set; }
        public decimal correlativo { get; set; }
        public Nullable<decimal> Ordinario { get; set; }
        public Nullable<decimal> Bonificaciones { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<decimal> Extras { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual formaPago formaPago { get; set; }
        public virtual Planilla Planilla { get; set; }
    }
}
