//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePlanilla
    {
        public int idPlanilla { get; set; }
        public int idColaborador { get; set; }
        public int idFormaPago { get; set; }
        public int anio { get; set; }
        public int mes { get; set; }
        public int correlativo { get; set; }
        public decimal Ordinario { get; set; }
        public decimal Bonificaciones { get; set; }
        public decimal Descuentos { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Extras { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual formaPago formaPago { get; set; }
        public virtual Planilla Planilla { get; set; }
    }
}
