//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public decimal idColaborador { get; set; }
        public decimal idTipoDireccion { get; set; }
        public decimal idDireccion { get; set; }
        public string descripcion { get; set; }
        public string idPais { get; set; }
        public Nullable<decimal> idDepartamento { get; set; }
        public Nullable<decimal> idMunicipio { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual TipoDireccion TipoDireccion { get; set; }
    }
}
