//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_LABORAGT_Entities : DbContext
    {
        public DB_LABORAGT_Entities()
            : base("name=DB_LABORAGT_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<Bonos> Bonos { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<ColaboradorDescuento> ColaboradorDescuento { get; set; }
        public virtual DbSet<CuentaDeposito> CuentaDeposito { get; set; }
        public virtual DbSet<CuentaEmpresa> CuentaEmpresa { get; set; }
        public virtual DbSet<DatoFamiliar> DatoFamiliar { get; set; }
        public virtual DbSet<DatosAcademicos> DatosAcademicos { get; set; }
        public virtual DbSet<DatosLaborales> DatosLaborales { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetallePlanilla> DetallePlanilla { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaColaborador> EmpresaColaborador { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<formaPago> formaPago { get; set; }
        public virtual DbSet<Identificacion> Identificacion { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<NivelAcademico> NivelAcademico { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Parentezco> Parentezco { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<Profesion> Profesion { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<ReferenciaColaborador> ReferenciaColaborador { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<TipoCuenta> TipoCuenta { get; set; }
        public virtual DbSet<TipoDescuento> TipoDescuento { get; set; }
        public virtual DbSet<TipoDireccion> TipoDireccion { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoReferencia> TipoReferencia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
