//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboraGTv0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciaColaborador
    {
        public decimal idColaborador { get; set; }
        public string idReferencia { get; set; }
        public string nombre { get; set; }
        public string telefono1 { get; set; }
        public string direccion { get; set; }
        public string edad { get; set; }
        public decimal idTipoReferencia { get; set; }
        public decimal idParentezco { get; set; }
        public decimal idProfesion { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Parentezco Parentezco { get; set; }
        public virtual Profesion Profesion { get; set; }
        public virtual TipoReferencia TipoReferencia { get; set; }
    }
}
